### ISSUE TITLE
Definition of Log-Loss 

### ISSUE THREAD

**Issue by yavuzsunor** [h2oai/tutorials#45]
Hi, I'm a Data Scientist based in NYC. 
I came across the definition of log-loss at "Introduction to Machine Learning with H2O - Part 1" with the link https://h2oai.github.io/tutorials/introduction-to-machine-learning-with-h2o-part-1/#3. It says log-loss ranges from 0 to 1 which is not correct I believe. As I recall and if not missing something, there is no upper limit on that. You may want to correct that.   
Resource: http://wiki.fast.ai/index.php/Log_Loss

Best,
Yavuz

**Comment by FrankJVA** [comment]
Hi @yavuzsunor,
Thank you for filing an issue. We will work on updating the definition of log-loss. Thank you so much for your contribution.
Regards,
Franklin

**Comment by Castro38** [comment]
The definition of Log loss has been updated for the following tutorials:
1.  [Machine Learning with H2O - Part -1 ](https://github.com/h2oai/tutorials/blob/master/H2O/introduction-to-machine-learning-with-h2o-part-1/introduction-to-machine-learning-with-h2o-part-1.md)
2. [Machine Learning Experiment Scoring and Analysis Tutorial - Financial Focus](https://github.com/h2oai/tutorials/blob/master/DriverlessAI/machine-learning-experiment-scoring-and-analysis/machine-learning-experiment-scoring-and-analysis.md)
