### ISSUE TITLE
Does H2o Driverless ai latest stable 1.8 version support Image Classification

### ISSUE THREAD

**Issue by vishal-meshram** [h2oai/tutorials#50]
I am using DAI for Image classification on my own dataset. After successful uploading dataset when I start predication I got the following error:

STATUS: FAILED
Data not in acceptable form, experiment parameters chosen invalid, or custom recipe invalid.
Error: No data left after dropping missing / constant columns. (Error Type: InvalidDataError). Experiment ID: b3ba16f4-151c-11ea-be40-0242ac110002

**Comment by mtanco** [comment]
Hi @vishal-meshram, we are working on out-of-the-box Computer Vision that would include image classification, but it is not currently available. 

By using the Custom Recipe functionality (https://github.com/h2oai/driverlessai-recipes) you can add in a transformer which takes URLs or file paths (on the Driverless AI system) and vectorizes them with a pre-trained model. The vectors are then used within Driverless AI models:

https://github.com/h2oai/driverlessai-recipes/blob/master/transformers/image/image_url_transformer.py

**Expected Data Format:**
|URL or File Path to Image| Other Input Columns (optional) | Value to Predict (Class or Number)|
|:-:|:-:|:-:|
|...|...|...|

**Comment by vishal-meshram** [comment]
Dear Sir,
Thank you very much for your reply. I tried the same process as mentioned
in your previous email but still getting the same error. I am unable to add
customized recipe in the driverless ai.

once again thanks for your help..

Thanks & regards,
- Vishal

**Comment by Castro38** [comment]
Hi @vishal-meshram,

Thank you for reaching out. Here is a video about using Driverless AI for image classification at [H2O World New York in Oct 2019](https://www.youtube.com/watch?v=gRraEabTX3o&feature=youtu.be). 

Yauhen Babakhin is a H2O.ai developer working on making this enhancement.  This capability is not yet Generally Available(GA).   It will be part of a future release. @ybabakhin is there a version of this that this professor can look at?  Would it be possible for him to collaborate with you on this?

In the future, you can ask product questions on our [slack channel](https://www.h2o.ai/slack-community/#community-form).

Regards,
Ana

**Comment by vishal-meshram** [comment]
Hi Ana,
Greetings!!!

Sorry for the late reply.. I am very much greatful for your reply. I am
already following Yauhen Babakhin about using Driverless AI for image
classification at H2O World New York in Oct 2019
<https://www.youtube.com/watch?v=gRraEabTX3o&feature=youtu.be>. I will get
in touch with  @ybabakhin for this issue.
Once again Thanks a lot..

Thanks & Regards,

- Vishal

**Comment by ybabakhin** [comment]
Hi @vishal-meshram,

Computer Vision stuff, and automatic image classification in particular, is not available in the previous DAI versions. We have now work-in-progress to add this functionality in one of the next DAI releases.
