### ISSUE TITLE
Naming Convention Consistency

### ISSUE THREAD

**Issue by mtanco** [h2oai/tutorials#68]
There are a few folder / file names that are inconsistent throughout this repo. It may be worth choosing a convention and sticking with it:

- [x] Read Me files: `README.md` vs. `readme.md`
- [ ] Tutorial folder names `get-started` vs. `getting-started`
- [x] Directory names `English Spacing` vs. `OneWordCaps` vs. `lower-case-dashes` (personally for the dashes)

Low priority

**Comment by Castro38** [comment]
Hi Michelle, 

Thank you for your feedback. I agree, the Read Me files should probably be all upper or lower case. I have made some updates for that. Regarding the tutorial folder names, the name of those two tutorials was decided with a specific intent in mind. I will circle back with those who gave me the title names and see what they think. I updated the one file that has the OneWordCaps for the main directory to English Spacing for legibility. The remaining subdirectories need to remain as lower-case-dashes for publishing on the landing page.
