### ISSUE TITLE
h2o SHAP predict contributions with MOJO

### ISSUE THREAD

**Issue by pbhat14** [h2oai/tutorials#85]
as per release (https://www.h2o.ai/blog/h2o-release-3-26-yau/) it is said that SHAP values can be retrieved from MOJO as well. However in there is no function such as h2o.mojo_predict_contributions or equivalent ?

Once model is imported : gbm_m=h2o.import_mojo('GBM_model_R.zip') and h2o.predict_contributions(gbm_m,data) is run ( note data is already a h2o data frame and h20 cluster is active )  , below is the output 
![image](https://user-images.githubusercontent.com/10569720/80164269-14cd9100-860b-11ea-8cb6-8846dcd9ee76.png)

There is another link (http://docs.h2o.ai/sparkling-water/2.2/latest-stable/doc/tutorials/shap_values.html) which doesn't give clear guidance on how to retrieve SHAP values in other than the sparking water h2o version. How can we extract SHAP values with a MOJO object directly without the need to spin off a cluster i.e. functions such as h2o.mojo_predict_df

**Comment by Castro38** [comment]
Hi @pbhat14,  thank you for your question. The focus of this H2O.ai Github repo/issues is on posting questions or issues regarding the H2O.ai [tutorials ](https://h2oai.github.io/tutorials/). We have a [Community Slack Channel
](https://www.h2o.ai/slack-community/) #h2o-core where you can post your question/issue regarding the H2O open-source platform. After posting your question on the channel, experts from the H2O.ai community will post a response. I will post your question on that channel. Once you join, you can look for the answer to your question/issue there.

Thanks,
The H2O.ai Tutorials Team
